force-app/main/default/objects/Airport__c/Airport__c.object-meta.xml
<CustomObject>
    <label>Airport</label>
    <nameField>
        <label>Airport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight__c/fields/Arrival__c.field-meta.xml
<CustomField>
    <fullName>Arrival__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Arrival</label>
    <referenceTo>Airport__c</referenceTo>
    <relationshipLabel>Flights</relationshipLabel>
    <relationshipName>Flights</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Departure__c.field-meta.xml
<CustomField>
    <fullName>Departure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departure</label>
    <referenceTo>Airport__c</referenceTo>
    <relationshipLabel>Flights (Departure)</relationshipLabel>
    <relationshipName>Departures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Distance_in_km__c.field-meta.xml
<CustomField>
    <fullName>Distance_in_km__c</fullName>
    <label>Distance (in km)</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/FlightControllerTest.cls
/*
 * Created By Zeeshan Ahmed
 * Created on 28th June 2022
 * Description: FlightControllerTest class to unit test the flight controller class
 * */
@isTest
public class FlightControllerTest {
	@testSetup
    public static void setup(){
        TestDataFactory.createAirports();
    }
    
    @isTest
    static void createFlightPositiveCase() {
        
        Id departureAirportId;
        Id arrivalAirportId;
        List<Airport__c> airportData=[SELECT Id,Name FROM Airport__c
                                      WHERE Name IN ('Barcelona','Madrid')
                                      LIMIT 2];
        
        for(Airport__c ap : airportData) {
            if(ap.Name == 'Barcelona'){
                departureAirportId = ap.Id;
            }else{
                arrivalAirportId = ap.Id;
            }
        }
        
        Flight__c flight = new Flight__c();
        flight.Arrival__c = arrivalAirportId;
        flight.Departure__c = departureAirportId;
        ApexPages.standardController stdCon = new ApexPages.standardController(flight);
        
        FlightController c = new FlightController(stdCon);

        Test.startTest();
        c.save();
        Test.stopTest();
        
        Flight__c createdFlight = [SELECT Id, Distance_in_km__c, Departure__c, Arrival__c
                                   FROM Flight__c
                                   WHERE ID =: flight.Id
                                   LIMIT 1 ];
        
        System.assertEquals(482.8, createdFlight.Distance_in_km__c.setScale(1),'Distance not calculated Successfully!'); 
    }
    
    @isTest
    static void createFlightNegativeCase() {
        
        Id departureAirportId;
        Id arrivalAirportId;
        List<Airport__c> airportData=[SELECT Id,Name FROM Airport__c
                                      WHERE Name IN ('Barcelona','Madrid')
                                      LIMIT 2];
        
        for(Airport__c ap : airportData) {
            if(ap.Name == 'Barcelona'){
                departureAirportId = ap.Id;
            }else{
                arrivalAirportId = ap.Id;
            }
        }
        
        Flight__c flight = new Flight__c();
        flight.Arrival__c = arrivalAirportId;
        flight.Departure__c = departureAirportId;
        ApexPages.standardController stdCon = new ApexPages.standardController(flight);
        
        FlightController c = new FlightController(stdCon);

        Test.startTest();
        c.save();
        
        Flight__c flight1 = new Flight__c();
        flight1.Arrival__c = arrivalAirportId;
        flight1.Departure__c = departureAirportId;
        ApexPages.standardController stdCon1 = new ApexPages.standardController(flight1);
        
        FlightController c1 = new FlightController(stdCon1);

        c1.save();
        Test.stopTest();
        
        System.assertEquals(null, Flight1.Id); 
    }
}